In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("kndrgdens_1.csv")
df.head(2)

,fullname,shortname,number,category,vid_uchrezhdeniya,organiz_pravov_forma,podchinenie,address,telephone,email,location
0,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 1439,1 439,Дошкольное образовательное учреждение,Детский сад компенсирующего вида,Бюджетное,Северо-Восточное окружное управление образования,"""127273 г. Москва, ул. Отрадная, д. 5 ""Б""",(499) 907-63-66,detsad1439@mail.ru,POINT(37.6076187 55.8591187)
1,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 938,938,Дошкольное образовательное учреждение,Детский сад,Бюджетное,Северо-Восточное окружное управление образования,"127349, город Москва, улица Лескова, дом 6 Г",(499) 909-00-44,detskiysad938@yandex.ru,POINT(37.5925685 55.8970746)

In [6]:
df['Latitude'] = pd.to_numeric(df['Latitude'], errors='coerce')
df['Longitude'] = pd.to_numeric(df['Longitude'], errors='coerce')
df['location'] = df.apply(
    lambda row: f"POINT({row['Longitude']} {row['Latitude']})"
    if pd.notna(row['Longitude']) and pd.notna(row['Latitude'])
    else None,
    axis=1
)
df.head()

,fullname,shortname,number,category,vid_uchrezhdeniya,organiz_pravov_forma,podchinenie,address,Latitude,Longitude,telephone,email,location
0,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 1264,1 264,Дошкольное образовательное учреждение,Детский сад,Бюджетное,Юго-Восточное окружное управление образования,"115432, г.Москва, ул. Трофимова,д.11",55.703335,37.668909,(495) 679-06-67,d_c1264@mail.ru; d_c1264_1@mail.ru; d-c1264@y...,POINT(37.6689089 55.7033346)
1,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 2642,2 642,Дошкольное образовательное учреждение,Детский сад,Бюджетное,Северное окружное управление образования,"125299, г. Москва, ул. Клары Цеткин, д. 15Б",55.820502,37.516988,(495) 601-46-94,detsad2642@mail.ru,POINT(37.5169885 55.8205021)
2,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 2198,2 198,Дошкольное образовательное учреждение,Детский сад комбинированного вида,Бюджетное,Восточное окружное управление образования,"107113, г. Москва, Поперечный просек д. 1А",55.794986,37.656089,(499) 269-89-82,gou.ds2198@gmail.com,POINT(37.6560889 55.7949863)
3,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 813,813,Дошкольное образовательное учреждение,Детский сад комбинированного вида,Бюджетное,Восточное окружное управление образования,"111402, г. Москва, ул. Кетчерская, д.6А",55.742684,37.823713,(495) 375-77-30,detskij-sad-813@mail.ru,POINT(37.8237126 55.7426839)
4,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 283,283,Дошкольное образовательное учреждение,Детский сад комбинированного вида,Бюджетное,Восточное окружное управление образования,"105484,г. Москва, 13-я Парковая ул.,д.30",55.806057,37.814724,(495) 468-54-28,dc283@yandex.ru,POINT(37.814724 55.806057)

In [7]:
# Удаление лишних столбцов
df = df.drop(columns=['Latitude', 'Longitude'])
df.head(3)
#df.tail(3)

,fullname,shortname,number,category,vid_uchrezhdeniya,organiz_pravov_forma,podchinenie,address,telephone,email,location
0,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 1264,1 264,Дошкольное образовательное учреждение,Детский сад,Бюджетное,Юго-Восточное окружное управление образования,"115432, г.Москва, ул. Трофимова,д.11",(495) 679-06-67,d_c1264@mail.ru; d_c1264_1@mail.ru; d-c1264@y...,POINT(37.6689089 55.7033346)
1,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 2642,2 642,Дошкольное образовательное учреждение,Детский сад,Бюджетное,Северное окружное управление образования,"125299, г. Москва, ул. Клары Цеткин, д. 15Б",(495) 601-46-94,detsad2642@mail.ru,POINT(37.5169885 55.8205021)
2,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 2198,2 198,Дошкольное образовательное учреждение,Детский сад комбинированного вида,Бюджетное,Восточное окружное управление образования,"107113, г. Москва, Поперечный просек д. 1А",(499) 269-89-82,gou.ds2198@gmail.com,POINT(37.6560889 55.7949863)

In [8]:
df.info()
#df.describe()
#df.columns
#df.shape

<class 'pandas.DataFrame'>
RangeIndex: 694 entries, 0 to 693
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fullname              694 non-null    str
 1   shortname             694 non-null    str
 2   number                694 non-null    str
 3   category              694 non-null    str
 4   vid_uchrezhdeniya     694 non-null    str
 5   organiz_pravov_forma  694 non-null    str
 6   podchinenie           694 non-null    str
 7   address               694 non-null    str
 8   telephone             694 non-null    str
 9   email                 694 non-null    str
 10  location              694 non-null    str
dtypes: str(11)
memory usage: 59.8 KB

In [9]:
df.to_csv("kndrgdens_2.csv", index=False, encoding="utf-8")